CREATE TYPE IF NOT EXISTS job_status_enum AS ENUM ('OPEN', 'IN_PROGRESS', 'CLOSED');

CREATE TYPE IF NOT EXISTS job_category_enum AS ENUM ('WEB_DEV', 'WRITING', 'DESIGN', 'MOBILE', 'DEVELOPMENT');

CREATE TYPE IF NOT EXISTS job_attachment_type_enum AS ENUM ('BRIEF', 'MOCKUP', 'REFERENCE', 'CONTRACT_TEMPLATE');