spring:
  application:
    name: proposal-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/freelancedb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@mongo:27017/freelancemongo?authSource=admin}
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:redispass}
    neo4j:
      uri: ${SPRING_NEO4J_URI:bolt://neo4j:7687}
      username: ${SPRING_NEO4J_USERNAME:neo4j}
      password: ${SPRING_NEO4J_PASSWORD:neo4jpass}

server:
  port: 8080

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes in milliseconds


jwt:
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef01234567}
  expiration: ${JWT_EXPIRATION_MS:86400000}


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/freelancedb
  data:
    neo4j:
      uri: bolt://localhost:7687
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/freelancemongo?authSource=admin
    redis:
      host: localhost