CREATE TYPE IF NOT EXISTS proposal_status_enum AS ENUM
('SUBMITTED', 'SHORTLISTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN');

CREATE TYPE IF NOT EXISTS milestone_status_enum AS ENUM
('PENDING', 'IN_PROGRESS', 'COMPLETED', 'APPROVED');