spring:
  application:
    name: contract-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://contract-postgres:5432/freelancedb-contracts}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${SPRING_MONGODB_URI:mongodb://root:rootpass@mongo:27017/freelancemongo?authSource=admin}}
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:redispass}

  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:cassandra}
    port: ${SPRING_CASSANDRA_PORT:9042}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:freelanceks}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: CREATE_IF_NOT_EXISTS

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef01234567}
  expiration: ${JWT_EXPIRATION_MS:86400000}



cache:
  type: redis
  redis:
    time-to-live: 600000  # 10 minutes in milliseconds
