apiVersion: v1
kind: Secret
metadata:
  name: proposal-postgres-secret
  namespace: freelance
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: freelancedb-proposals
