apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: api-gateway
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - api-gateway.freelance.svc.cluster.local:8080
      - job_name: user-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - user-service.freelance.svc.cluster.local:8080
      - job_name: job-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - job-service.freelance.svc.cluster.local:8080
      - job_name: proposal-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - proposal-service.freelance.svc.cluster.local:8080
      - job_name: contract-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - contract-service.freelance.svc.cluster.local:8080
      - job_name: wallet-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - wallet-service.freelance.svc.cluster.local:8080
      - job_name: rabbitmq
        metrics_path: /metrics
        static_configs:
          - targets:
              - rabbitmq.freelance.svc.cluster.local:15692
