apiVersion: v1
kind: ConfigMap
metadata:
  name: contract-service-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://contract-postgres:5432/freelancedb-contracts"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  FEIGN_USER_SERVICE_URL: "http://user-service:8080"
  FEIGN_JOB_SERVICE_URL: "http://job-service:8080"
  LOKI_URL: "http://loki:3100"
