apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: freelance
data:
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_JOB_SERVICE_URL: http://job-service:8080
  FEIGN_PROPOSAL_SERVICE_URL: http://proposal-service:8080
  FEIGN_CONTRACT_SERVICE_URL: http://contract-service:8080
  FEIGN_WALLET_SERVICE_URL: http://wallet-service:8080
