apiVersion: v1
kind: ConfigMap
metadata:
  name: proposal-service-configmap
  namespace: freelance
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://proposal-postgres:5432/freelancedb-proposals
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/freelancemongo?authSource=admin
  SPRING_MONGODB_URI: mongodb://root:rootpass@mongo:27017/freelancemongo?authSource=admin
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: redispass
  SPRING_NEO4J_URI: bolt://neo4j:7687
  SPRING_NEO4J_USERNAME: neo4j
  SPRING_NEO4J_PASSWORD: neo4jpass
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_JOB_SERVICE_URL: http://job-service:8080
  FEIGN_PROPOSAL_SERVICE_URL: http://proposal-service:8080
  FEIGN_CONTRACT_SERVICE_URL: http://contract-service:8080
  FEIGN_WALLET_SERVICE_URL: http://wallet-service:8080
