CREATE TYPE IF NOT EXISTS user_role_enum AS ENUM ('ADMIN', 'CLIENT', 'FREELANCER');

CREATE TYPE IF NOT EXISTS user_status_enum AS ENUM ('ACTIVE', 'DEACTIVATED');

CREATE TYPE IF NOT EXISTS proficiency_level_enum AS ENUM ('BEGINNER', 'INTERMEDIATE', 'EXPERT');