resources:
  - gateway/api-gateway.yaml
  - services/user-service.yaml
  - services/job-service.yaml
  - services/proposal-service.yaml
  - services/contract-service.yaml
  - services/wallet-service.yaml
  - postgres/user-postgres.yaml
  - postgres/job-postgres.yaml
  - postgres/proposal-postgres.yaml
  - postgres/contract-postgres.yaml
  - secrets/wallet-postgres-secret.yaml
  - pvcs/wallet-postgres-pvc.yaml
  - services/wallet-postgres-svc.yaml
  - statefulsets/wallet-postgres-statefulset.yaml
  - rabbitmq/rabbitmq.yaml
  - prometheus-configmap.yaml
  - grafana-dashboards.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
  - observability/loki.yaml
  - observability/neo4j.yaml
