apiVersion: v1
kind: Service
metadata:
  name: contract-postgres
  labels:
    app: contract-postgres
spec:
  selector:
    app: contract-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: contract-postgres
  labels:
    app: contract-postgres
spec:
  serviceName: contract-postgres
  replicas: 1
  selector:
    matchLabels:
      app: contract-postgres
  template:
    metadata:
      labels:
        app: contract-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: freelancedb-contracts
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
