apiVersion: v1
kind: Secret
metadata:
  name: job-postgres-secret
  namespace: freelance
type: Opaque
stringData:
  POSTGRES_USER:     postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB:       freelancedb-jobs
---
apiVersion: v1
kind: Service
metadata:
  name: job-postgres
  namespace: freelance
  labels:
    app: job-postgres
spec:
  selector:
    app: job-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: job-postgres
  namespace: freelance
  labels:
    app: job-postgres
spec:
  serviceName: job-postgres
  replicas: 1
  selector:
    matchLabels:
      app: job-postgres
  template:
    metadata:
      labels:
        app: job-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: job-postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi