apiVersion: v1
kind: Service
metadata:
  name: proposal-postgres
  namespace: freelance
spec:
  clusterIP: None
  selector:
    app: proposal-postgres
  ports:
    - port: 5432
      targetPort: 5432
